.TH STORMY 1	
.SH NAME
stormy \- install and configure tor onion services
.SH SYNOPSIS
.B stormy
[option]
.SH DESCRIPTION
.B stormy
install and configure tor onion services
.SH EXAMPLES
.TP
.BR stormy
Starts Stormy's wizard to guide you through options for setup.
.TP
.BR "stormy --ghost"
Installs the Ghost blogging platform and configures the onion service.
.SH OPTIONS
.TP
.BR \-\-wizard
Launches the wizard manually.
.TP
.BR \-g ", " \-\-ghost
Installs the Ghost blogging platform and configures the onion service.
.TP
.BR \-\-cozy ", " \-\-cloud
Sets up Cozy Cloud and all modules (calendar, tasklist, files)
.TP
.BR \-\-rss
Installs tt-rss reader for lightweight, censorship-resistant reading of RSS feeds.
.TP
.BR \-w ", " \-\-website
Installs a basic webserver with hidden service, ready for users to add their static website.
.TP
.BR \-t ", " \-\-tor
Configures only the tor settings. Ideal for offering an existing website as an onion site.
.TP
.BR \-\-irc
Installs and configures an IRC server (ircd-hybrid)
.TP
.BR \-\-jabber
Configures ejabberd XMPP chat server for use with a client.