.TH STORMY 1	
.SH NAME
stormy \- install and configure tor hidden services
.SH SYNOPSIS
.B stormy
.B stormy
[\fB\option\fR]
.SH DESCRIPTION
.B stormy
install and configure tor hidden services
.SH EXAMPLES
.TP
.BR stormy
Starts Stormy's wizard to guide you through options for setup.
.BR stormy --ghost
Installs the Ghost blogging platform and configures the hidden service.
.SH OPTIONS
.TP
.BR \-g ", " \-\-ghost
Installs the Ghost blogging platform and configures the hidden service.
.BR \-\-cozy ", " \-\-cloud
Sets up Cozy Cloud and all modules (calendar, tasklist, files)
.BR \-\-wiki ", " \-\-moinmoin
Installs moinmoin, a collaborative wiki environment.
.BR \-\-rss
Installs tt-rss reader for lightweight, censorship-resistant reading of RSS feeds.
.BR \-w ", " \-\-website
Installs a basic webserver with hidden service, ready for users to add their static website.
.BR \-t ", " \-\-tor
Configures only the hidden service. Ideal for layering a hidden service on top of an existing website.
.BR \-\-irc
Installs and configures an IRC server (ircd-hybrid)
.BR \-\-jabber
Configures ejabberd XMPP chat server for use with a client.
.BR \-\-purge <nick>
Deletes a hidden service and all related files with a given nickname.